- id: '1638178228067'
  alias: APP Lumière Salon
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Lumière Salon
  condition: []
  action:
  - type: toggle
    device_id: ac5cf887c79d094884301ca8d4d2ba3b
    entity_id: light.salon
    domain: light
  mode: single
- id: '1638178485641'
  alias: APP Lumière Cuisine
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Lumière Cuisine
  condition: []
  action:
  - type: toggle
    device_id: d666a0fddcf0d1eba34599fa20e7c6b8
    entity_id: light.cuisine
    domain: light
  mode: single
- id: '1638179266611'
  alias: APP Lumière Chambre
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Lumière Chambre
  condition: []
  action:
  - type: toggle
    device_id: 57395e5d594fa9413b03a8143237b878
    entity_id: light.chambre
    domain: light
  mode: single
- id: '1638179297385'
  alias: APP Lumière Bureau
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Lumière Cuisine
  condition: []
  action:
  - type: toggle
    device_id: 3d1714f111ebc8f8813cc963821b2bb2
    entity_id: light.bureau
    domain: light
  mode: single
- id: '1638981386018'
  alias: App Lumière Couloir
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Lumière Couloir
  condition: []
  action:
  - type: toggle
    device_id: c9eeb066ccf7373fd696715ad6f41bc1
    entity_id: light.couloir_chambre
    domain: light
  - type: toggle
    device_id: a2d6d3aed334fb11c4a81dffb93aecfd
    entity_id: light.couloir_entree
    domain: light
  mode: single
- id: '1638982078550'
  alias: Motion Sensor - Couloir Entrée - Up - Jour
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: e13cb800cc0e8f9a4c29600e33ac0e3f
    entity_id: binary_sensor.sensor_couloir_entree_motion
    domain: binary_sensor
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: time
        after: 08:00
        before: '23:59'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - condition: time
        after: '10:00'
        before: '23:59'
        weekday:
        - sat
        - sun
    - type: is_illuminance
      condition: device
      device_id: e13cb800cc0e8f9a4c29600e33ac0e3f
      entity_id: sensor.sensor_couloir_entree_illuminance
      domain: sensor
      below: 10
    - condition: device
      type: is_off
      device_id: a2d6d3aed334fb11c4a81dffb93aecfd
      entity_id: light.couloir_entree
      domain: light
    - condition: or
      conditions:
      - condition: sun
        before: sunrise
        before_offset: '30'
      - condition: sun
        after: sunset
        after_offset: '30'
  action:
  - type: turn_on
    device_id: a2d6d3aed334fb11c4a81dffb93aecfd
    entity_id: light.couloir_entree
    domain: light
  mode: single
- id: '1638984204571'
  alias: Motion Sensor - Couloir Entrée - Down
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: e13cb800cc0e8f9a4c29600e33ac0e3f
    entity_id: binary_sensor.sensor_couloir_entree_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition:
  - condition: and
    conditions:
    - condition: device
      type: is_on
      device_id: a2d6d3aed334fb11c4a81dffb93aecfd
      entity_id: light.couloir_entree
      domain: light
    - condition: or
      conditions:
      - condition: sun
        before: sunrise
      - condition: sun
        after: sunset
  action:
  - type: turn_off
    device_id: a2d6d3aed334fb11c4a81dffb93aecfd
    entity_id: light.couloir_entree
    domain: light
  mode: single
- id: '1638984866774'
  alias: APP Lampadaire Salon
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Lampadaire Salon
  condition: []
  action:
  - type: toggle
    device_id: ad9872da70d86bd16774e0cf17cffe5e
    entity_id: light.lampadaire_salon
    domain: light
  mode: single
- id: '1638985224006'
  alias: Motion Sensor - Couloir Chambre - Up - Jour
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: e47c2e9652be0ecd1859f2b9d1f39f2c
    entity_id: binary_sensor.sensor_couloir_chambre_motion
    domain: binary_sensor
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: time
        after: 08:00
        before: '23:59'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - condition: time
        after: '10:00'
        before: '23:59'
        weekday:
        - sat
        - sun
    - type: is_illuminance
      condition: device
      device_id: e47c2e9652be0ecd1859f2b9d1f39f2c
      entity_id: sensor.sensor_couloir_chambre_illuminance
      domain: sensor
      below: 10
    - condition: device
      type: is_off
      device_id: c9eeb066ccf7373fd696715ad6f41bc1
      entity_id: light.couloir_chambre
      domain: light
    - condition: or
      conditions:
      - condition: sun
        before: sunrise
        before_offset: '30'
      - condition: sun
        after: sunset
        after_offset: '30'
  action:
  - type: turn_on
    device_id: c9eeb066ccf7373fd696715ad6f41bc1
    entity_id: light.couloir_chambre
    domain: light
  mode: single
- id: '1638985454413'
  alias: Motion Sensor - Couloir Chambre - Down
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: e47c2e9652be0ecd1859f2b9d1f39f2c
    entity_id: binary_sensor.sensor_couloir_chambre_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: sun
        before: sunrise
      - condition: sun
        after: sunset
    - condition: device
      type: is_on
      device_id: c9eeb066ccf7373fd696715ad6f41bc1
      entity_id: light.couloir_chambre
      domain: light
  action:
  - type: turn_off
    device_id: c9eeb066ccf7373fd696715ad6f41bc1
    entity_id: light.couloir_chambre
    domain: light
  mode: single
