---
#-
#                   __ _                       _   _
#   ___ ___  _ __  / _(_) __ _ _   _ _ __ __ _| |_(_) ___  _ __
#  / __/ _ \| '_ \| |_| |/ _` | | | | '__/ _` | __| |/ _ \| '_ \
# | (_| (_) | | | |  _| | (_| | |_| | | | (_| | |_| | (_) | | | |
#  \___\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\__|_|\___/|_| |_|
#                        |___/
#
#- from github.com/squelix/home-assistant-config
homeassistant: !include includes/homeassistant.yaml
default_config:
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

spotify: !include includes/spotify.yaml
ble_monitor: !include includes/ble_monitor.yaml
sensor: !include includes/sensor.yaml
light: !include includes/lights.yaml

frontend:
  themes: !include_dir_merge_named themes
