background: var(--background-image)
title: Maison
views:
  - path: default_view
    title: Home
    icon: mdi:home
    badges:
      - entity: person.mickael_depardon
      - entity: person.sharleen_mullet
    cards:
      - type: weather-forecast
        entity: weather.grenoble
      - type: entities
        entities:
          - entity: binary_sensor.rpi_power_status
          - entity: binary_sensor.updater
          - entity: sensor.memory_use_percent
          - entity: sensor.temperature_cpu
          - entity: sensor.disk_use_percent
        title: Capteur binaire
      - type: entities
        entities:
          - sensor.co2_intensity
          - sensor.grid_fossil_fuel_percentage
          - sensor.hacs
        title: Capteur
      - type: media-control
        entity: media_player.spotify_mikador_le_pacificateur
      - type: media-control
        entity: media_player.shield
      - type: sensor
        entity: sensor.ble_humidity_thermometre
        graph: line
        detail: 2
        name: Humidité
      - type: sensor
        entity: sensor.ble_temperature_thermometre
        graph: line
        detail: 2
        name: Température
      - type: entities
        title: Lumières
        show_header_toggle: false
        entities:
          - type: custom:fold-entity-row
            open: false
            head:
              type: custom:slider-entity-row
              name: Salon
              entity: light.lumieres_du_salon
              hide_state: true
              toggle: true
              icon: mdi:sofa
            entities:
              - entity: light.salon
                name: Plafond salon
              - light.lampadaire_salon
          - type: custom:fold-entity-row
            open: false
            head:
              name: Couloir
              type: custom:slider-entity-row
              entity: light.lumieres_du_couloir
              hide_state: true
              toggle: true
              icon: mdi:door
            entities:
              - entity: light.couloir_chambre
                name: Chambre
              - entity: light.couloir_entree
                name: Entrée
          - entity: light.bureau
            name: Bureau
            icon: mdi:desk
          - entity: light.chambre
            name: Chambre
            icon: mdi:bed-king
          - entity: light.cuisine
            name: Cuisine
            icon: mdi:countertop-outline
      - type: entities
        entities:
          - entity: sensor.sensor_couloir_entree_illuminance
            name: Light level
          - entity: binary_sensor.sensor_couloir_entree_motion
            name: Motion
          - entity: sensor.sensor_couloir_entree_temperature
            name: Temperature
        title: Motion Sensor Couloir Entrée
      - type: entities
        entities:
          - entity: sensor.sensor_couloir_chambre_illuminance
            name: Light level
          - entity: binary_sensor.sensor_couloir_chambre_motion
            name: Motion
          - entity: sensor.sensor_couloir_chambre_temperature
            name: Temperature
        title: Motion sensor Couloir Chambre
  - title: Graphiques
    path: graphiques
    icon: mdi:chart-areaspline
    type: sidebar
    badges: []
    cards:
      - type: statistics-graph
        entities:
          - sensor.ble_temperature_thermometre
        title: Température Salon
        days_to_show: 31
      - type: statistics-graph
        entities:
          - sensor.ble_humidity_thermometre
        days_to_show: 31
        title: Humidité Salon
      - type: statistics-graph
        entities:
          - sensor.sensor_couloir_entree_temperature
        days_to_show: 31
        title: Température Entrée
      - type: statistics-graph
        entities:
          - sensor.sensor_couloir_chambre_temperature
        days_to_show: 31
        title: Température Chambres
  - icon: mdi:chart-bell-curve
    title: Raspberry
    path: raspberry
    type: sidebar
    badges: []
    cards:
      - type: statistics-graph
        entities:
          - sensor.memory_use_percent
        days_to_show: 365
        title: RAM
      - type: statistics-graph
        entities:
          - sensor.disk_use_percent
        days_to_show: 365
        chart_type: line
        title: Disque
      - type: history-graph
        entities:
          - sensor.temperature_cpu
        hours_to_show: 24
        refresh_interval: 0
        title: Température CPU
