---
#-
#  _ _       _     _
# | (_) __ _| |__ | |_ ___
# | | |/ _` | '_ \| __/ __|
# | | | (_| | | | | |_\__ \
# |_|_|\__, |_| |_|\__|___/
#      |___/
#
#- from github.com/squelix/home-assistant-config
- platform: group
  name: Lumières du salon
  unique_id: lights.salon
  entities:
    - light.hue_smart_plug_1
    - light.salon

- platform: group
  name: Lumières du couloir
  unique_id: lights.couloir
  entities:
    - light.hue_white_lamp_2
    - light.hue_white_lamp_1

- platform: group
  name: Lumières de la cuisine
  unique_id: lights.cuisine
  entities:
    - light.cuisine

- platform: group
  name: Lumières de la chambre
  unique_id: lights.chambre
  entities:
    - light.chambre

- platform: group
  name: Lumières du bureau
  unique_id: lights.bureau
  entities:
    - light.bureau
